name: twitter
author: sh4869 <nobuk4869@gmail.com> # name <email>
homepage: https://github.com/sh4869/twitter.dart # https://github.com/user/repo
#software 365
version: 0.5.2
environment:
  sdk: ">=1.8.0 <2.0.0"
description: Twitter API Library
dependencies:
  oauth2: "^1.2.0"
  http: "^0.11.3+16"
dev_dependencies:
  test: '>=0.12.3+6 <0.13.0'
